[package]
name = "postmodern_htmx_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0.6"
tera = "1.19.1"
lazy_static = "1.4.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
rand = "*"